void main() {
   var cv = "CURRICULUM VITAE";
  String name = "MUHAMMAD ADNAN";
  print(cv);
  print(name);
  String fn = "MUHAMMAD MUMTAZ";
  print (fn);
  String address = "Orangi Town Karachi Sector-10";
  print(address);
  int number = 03108123796;
  print(number);
  String email = "nandaswati8123796@gmail.com";
  print(email);
  String dateofbirth = "28:12:2021";
  print(dateofbirth);
  bool age = 19>18 ;
  print (age);
  String clas1 = "Classes";
  String clas2 = '=[10th,12th]';
  print (clas1+''+clas2);
  num a = 18;
  num b =19.3;
  print (a+b);
  print ("My age is :${18}");
  int c =12;
  int d =13;
  int output = c*d;
  print (output);
  int e =30;
  int f =2;
  int check=e%f;
  print ("check is :${check}"); 
  var g = 2;
  print(g);
  var h = 12.4;
  print (h);
  var i ="Muhammad Adnan";
  print(i);
  var j="12.3";
  print (g+h);
  print(i+j);
 
  double k =12.3;
  double l =13.2;
  print (k+l);
  num m =12;
  num n =12.3;
  print(m/n);
  String o = "My name is Muhammad Adnan";
  String p = "My age is 19";
    print (o);
  print(p);
  String q = 'My age is 12.3';
  print (q);
  bool r = 100<50;
  print(r);
  bool s = 100>50;
  print(s);